### ISSUE TITLE
Error when opening current example

### ISSUE THREAD

**Issue by tompro** [peermaps/eyros#26]
When opening the current example the map fails with the following error in Brave browser. Tried with both:
https://ipfs.io/ipfs/QmS24zmgDz2jFdakvd6aT6sRXSGRXWJaB62aPTbvmpguBB/
ipfs://bafybeibwvqwjcptcsl5zm4gedug5mlfsltvcirxffm2zgjr5hudxct6jmy/

```
Uncaught (in promise) RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at module.exports ((index):3208)
    at module.exports ((index):2701)
    at onDone ((index):6630)
    at notifyProgress ((index):11787)
    at onReadyStateChange ((index):11521)
    at XMLHttpRequest.xhr.onreadystatechange ((index):11471)
```

**Comment by substack** [comment]
Should be fixed in f4162f57fef7b979b7fa576b6bab262a63bb8f3d.

This version has the updated version of eyros:
https://ipfs.io/ipfs/Qmb4eNFHMoDpd5qxZsLuHxfTSwvzYnR6ReUtXqESEeD2aW/#bbox=-149.91,61.213,-149.89,61.223
